#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/crashbit/Development/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/crashbit/Desktop/cm-2022-1/sesion_08/session_11/containers_demo"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/crashbit/Desktop/cm-2022-1/sesion_08/session_11/containers_demo/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ=="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/crashbit/Desktop/cm-2022-1/sesion_08/session_11/containers_demo/.dart_tool/package_config.json"
